### ISSUE TITLE
Shuffle in beleaguered castle

### ISSUE THREAD

**Issue by Ygarr** [Tomin1/patience-deck#13]
Please add ability to in-game shuffle cards not in foundation without restart current game or creating new game

**Comment by Ygarr** [comment]
...and ability to move stack of descent card of same suit like one card.
And ability to gather cards not to foundation of same suit not only descending but ascending too.

**Comment by Tomin1** [comment]
Thank you for sharing your improvement ideas. These are feature requests that should be directed to [GNOME Aisleriot](https://gitlab.gnome.org/GNOME/aisleriot/), the upstream of the game implementations. I'm closing this here as it's not really something that can be improved in Patience Deck alone.

However here are some comments of mine about these specific improvements:
> Please add ability to in-game shuffle cards not in foundation without restart current game or creating new game

A nice idea. It would be a new feature that no game already has because the engine's (scheme language) interface doesn't support it, but I think it could be useful for more games than just Beleaguered Castle. Of course it also requires an implementation for each game separately.

> ...and ability to move stack of descent card of same suit like one card.

This should be something that can be implemented in Beleaguered Castle implementation without interface changes and thus no changes in Patience Deck should be required apart from pulling updated game implementations from Aisleriot.

> And ability to gather cards not to foundation of same suit not only descending but ascending too.

I think this would change the nature of the game quite a bit and might warrant another variant or at least an option in settings. As an example, there is another variant called Streets and Alleys and I think the only difference is that there are no aces in the foundations at the beginning of the game. This is also something which can be implemented by changing the game implementation and it doesn't really need changes in Patience Deck itself.
