### ISSUE TITLE
Disappearing cards on Patience Deck 0.5.1-1 ?

### ISSUE THREAD

**Issue by sviscapi** [Tomin1/patience-deck#3]
Dear @Tomin1 

I'm having a lot of fun with Patience Deck 0.5.1-1 on SFOS 4.1 / Xperia 10 II (64 bits). Thank you very much for porting this game to SailfishOS :)

On some not so rare occurrences I stumble upon a bug where cards seem to disappear, making the current game impossible to complete (see screenshot below).

As per the screenshot, one can see that there's one deal left, yet the stock in the upper left corner is empty...

Please let me know if I could do something on my end to help you pinpoint this issue.

Best regards,

Samuel

![Capture d'écran_20210819_001](https://user-images.githubusercontent.com/5636076/130086740-ae1cc5f5-1983-4f88-b515-1e1f3e5579e9.png)

**Comment by sviscapi** [comment]
Dear @Tomin1 ,

A similar bug happened this morning, see screenshot below. Where has the Queen of Hearts gone ?

![Capture d'écran_20210820_001](https://user-images.githubusercontent.com/5636076/130202519-04158fca-47bb-49ed-aabd-1170b45bb99b.png)

Best regards,

Samuel

**Comment by Tomin1** [comment]
Thank you for your report!

In the first picture you seem to have 52 cards on the table, counting all visible cards and those that I assume are hidden in foundations, so I don't think any of them are missing. You have a deal left because you didn't need to use all of them to empty stock pile. GNOME Aisleriot behaves the same way and as far as I can tell there is no error here.

In the second picture you have a real issue that I believe I've also seen. It's usually hard to reproduce when you try but it happens occasionally while playing the game. Did you use double tapping to move cards to foundation? My best guess at the moment is that there is some slight chance that double tapping can confuse the scheme side of the code because it hasn't yet finished all the moves. Typically this happens near the end of the game when you move many cards to foundations by double clicking them. I plan to try playing this game some more on the emulator, hoping that a slower environment will have greater chance of reproducing it. In any case I plan to add some checks to (double) clicking so that it can't happen before the previous move has finished.

One more thing, Patience Deck is not a port of GNOME Aisleriot. It's a complete re-implementation of the game engine and UI, only reusing the artwork, game manuals and scripts for the games. Ports are modifications of the original software to fit them to new environments, usually made so that they are able to join the work back to the original project. In this case these are two separate projects with mostly different code bases (game scripts are considered as code and they are shared). :)

**Comment by sviscapi** [comment]
Dear @Tomin1 ,

Thank you very much for your quick reply, really appreciated.

You are obviously right about the first screenshot, there is no problem with this one, sorry for the confusion.

Regarding the second screenshot, I indeed double tap to move cards to foundation.

And you are also right about Patience Deck not being a port of Gnome Aisleriot. I didn't mean to belittle your work, sorry again about that. If I understand correctly, Gnome Aisleriot uses GTK whereas Patience Deck must be using some sort of combination between QT, QML and C++. I'm certain you put in a lot of work to make this game fit the SFOS UI :)

Best regards,

Samuel

**Comment by Tomin1** [comment]
Oh, I didn't think that you belittled my work or anything. It's okay. I just find it a common misconception of the relationship of these two projects. Or maybe people just tend to use the wrong word because they are more familiar with forks and ports.

**Comment by Tomin1** [comment]
@sviscapi Hi! Please try the just released 0.6 version. It has many fixes to card dragging and engine-ui interaction and I hope it fixes also your issue. The new version can be downloaded on [releases page](https://github.com/Tomin1/patience-deck/releases/tag/0.6) and from [Open Repos](https://openrepos.net/content/tomin/patience-deck) right now and it will appear on Jolla Store after QA.

**Comment by Tomin1** [comment]
I haven't heard back from this but since there have been so many fixes and I haven't seen any issues. I'll close this. Please comment or open a new issue if there is still something wrong. And thanks for reporting again!
